'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { PUBLIC_API_BASE_URL } from '@/lib/env.public';

export function ForgotPasswordClient({ lang }: { lang: string }) {
  const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setMessage(''); try { const response = await fetch(`${PUBLIC_API_BASE_URL}/api/account/password-reset/`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) }); const data = await response.json().catch(() => ({})); setMessage(data.detail || 'If an account exists for this email, we have sent instructions.'); } catch { setMessage('If an account exists for this email, we have sent instructions.'); } finally { setLoading(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-slate-100 p-6"><section className="w-full max-w-md rounded-xl bg-white p-8 text-slate-900 shadow"><h1 className="text-3xl font-black">Recover your account</h1><p className="mt-2 text-slate-600">Enter the verified email address for your account.</p><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-semibold">Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-1 w-full rounded border border-slate-300 p-2 font-normal" /></label><button disabled={loading} className="w-full rounded bg-blue-700 px-4 py-2 font-bold text-white disabled:opacity-60">{loading ? 'Sending…' : 'Send recovery instructions'}</button></form>{message && <p className="mt-4 text-sm text-emerald-700">{message}</p>}<Link className="mt-6 inline-block text-sm font-semibold text-blue-700" href={`/${lang}/login`}>Return to sign in</Link></section></main>;
}

export function ResetPasswordClient({ lang }: { lang: string }) {
  const token = useSearchParams().get('token') || '';
  const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [message, setMessage] = useState(''); const [done, setDone] = useState(false); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setMessage(''); try { const response = await fetch(`${PUBLIC_API_BASE_URL}/api/account/password-reset/confirm/`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token, new_password: password, confirm_password: confirm }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || 'This password reset link is invalid or expired.'); setDone(true); setMessage('Password created. You can now sign in normally.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to reset your password.'); } finally { setLoading(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-slate-100 p-6"><section className="w-full max-w-md rounded-xl bg-white p-8 text-slate-900 shadow"><h1 className="text-3xl font-black">Create a new password</h1>{done ? <><p className="mt-4 text-emerald-700">{message}</p><Link className="mt-6 inline-block rounded bg-blue-700 px-4 py-2 font-bold text-white" href={`/${lang}/login`}>Sign in</Link></> : <form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-semibold">New password<input required minLength={8} type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-1 w-full rounded border border-slate-300 p-2 font-normal" /></label><label className="block text-sm font-semibold">Confirm password<input required minLength={8} type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} className="mt-1 w-full rounded border border-slate-300 p-2 font-normal" /></label>{message && <p className="text-sm text-red-700">{message}</p>}<button disabled={loading || !token} className="w-full rounded bg-blue-700 px-4 py-2 font-bold text-white disabled:opacity-60">{loading ? 'Saving…' : 'Create password'}</button></form>}</section></main>;
}
