# Generated by Django 5.0.9 on 2025-12-12 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('cta_href', models.URLField(blank=True)),
                ('cta_secondary_label', models.CharField(blank=True, max_length=100)),
                ('cta_secondary_href', models.URLField(blank=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('page', 'key')},
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('href', models.URLField(blank=True)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.section')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
