# Generated by Django 5.0.9 on 2025-12-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
