# Generated by Django 5.0.9 on 2025-12-13 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_section_body'),
        ('listings', '0006_add_media_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionBusinessPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the section')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.business')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_picks', to='content.section')),
            ],
            options={
                'verbose_name': 'Section business pick',
                'verbose_name_plural': 'Section business picks',
                'ordering': ['order', 'id'],
                'unique_together': {('section', 'business')},
            },
        ),
    ]
