# Generated by Django 5.0.9 on 2025-12-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroEffectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('opacity', models.FloatField(default=0.8, help_text='Overall opacity of the snow effect (0.0 - 1.0).')),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Rough density/speed preset for the effect.', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero effect settings',
                'verbose_name_plural': 'Hero effect settings',
            },
        ),
    ]
