# Generated by Django 5.0.9 on 2025-12-11 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiTextGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Machine key (e.g. 'home', 'search', 'header').", max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'UI text group',
                'verbose_name_plural': 'UI text groups',
            },
        ),
        migrations.CreateModel(
            name='UiTextTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('pt', 'Portuguese'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German')], max_length=5)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hero_settings.uitextgroup')),
            ],
            options={
                'verbose_name': 'UI text translation',
                'verbose_name_plural': 'UI text translations',
                'unique_together': {('group', 'language')},
            },
        ),
    ]
