# Generated by Django 5.0.9 on 2025-12-11 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Machine key for this category (e.g. 'guides', 'updates').", max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog category',
                'verbose_name_plural': 'Blog categories',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Primary slug used in URLs (usually English).', max_length=150, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('hero_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Optional manual publish datetime; can be used for ordering.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('pt', 'Portuguese'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German')], max_length=5)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog category translation',
                'verbose_name_plural': 'Blog category translations',
                'unique_together': {('category', 'language')},
            },
        ),
        migrations.CreateModel(
            name='BlogPostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('pt', 'Portuguese'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German')], max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Language-specific slug. Primarily for display; API URLs will use the base post.slug.', max_length=200)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=True, help_text='Whether this language version is published (post status must also be published).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog post translation',
                'verbose_name_plural': 'Blog post translations',
                'unique_together': {('post', 'language')},
            },
        ),
    ]
