# Generated by Django 5.0.9 on 2025-12-11 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Machine key for this sidebar slot (e.g. 'blog_sidebar', 'search_sidebar').", max_length=80, unique=True)),
                ('name', models.CharField(help_text='Human-readable name for admin.', max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slot is displayed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sidebar slot',
                'verbose_name_plural': 'Sidebar slots',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SidebarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the widget.', max_length=200)),
                ('item_type', models.CharField(choices=[('html', 'Custom HTML'), ('image_banner', 'Image Banner'), ('text_block', 'Text Block'), ('affiliate_ad', 'Affiliate Ad')], default='html', max_length=20)),
                ('content_html', models.TextField(blank=True, help_text='Raw HTML content (for html type) or affiliate tracking code.')),
                ('content_text', models.TextField(blank=True, help_text='Plain text content (for text_block type).')),
                ('image_url', models.URLField(blank=True, help_text='Image URL (for image_banner type).')),
                ('link_url', models.URLField(blank=True, help_text='Target URL for clickable items.')),
                ('link_text', models.CharField(blank=True, help_text='Link text/CTA.', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the slot.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is displayed.')),
                ('css_classes', models.CharField(blank=True, help_text='Optional CSS classes to apply to this widget.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ui.sidebarslot')),
            ],
            options={
                'verbose_name': 'Sidebar item',
                'verbose_name_plural': 'Sidebar items',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
