'use client';

import { useEffect, useState, type CSSProperties } from 'react';
import { ChevronLeft, ChevronRight, Eye, EyeOff, Globe2, ImagePlus, Mail, MapPin, MessageCircle, Phone, X } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { normalizeSpokenLanguages, spokenLanguageDetails, spokenLanguageName } from '@/lib/spokenLanguages';
import { resolvePresentationStyle } from '@/lib/presentationStyle';
import type { ClaimedListingViewData } from './ClaimedListingRenderer';

type CanvasValue = ClaimedListingViewData & { category_id?: number | string | null; city_id?: number | string | null; visibility: Record<string, boolean> };
type Props = {
  listing: CanvasValue;
  mode: 'editing' | 'preview' | 'public';
  categories?: Array<{ id: number; name: string }>;
  cityOptions?: Array<{ id: number; name: string }>;
  onChange?: (field: string, value: string | number | string[] | Record<string, boolean>) => void;
  onLogoUpload?: (file: File | undefined) => void;
  onBackgroundUpload?: (file: File | undefined) => void;
  allowMediaUpload?: boolean;
  uploading?: boolean;
};

// The postcard is designed at this proportion. Responsive instances scale
// this same canvas instead of acquiring a different layout at each width.
export const POSTCARD_CANVAS_WIDTH = 1600;
export const POSTCARD_CANVAS_HEIGHT = 900;

const FLAG_ASSET_CODES = new Set(['at', 'be', 'bg', 'cy', 'cz', 'de', 'dk', 'ee', 'es', 'eu', 'fi', 'fr', 'gr', 'hr', 'hu', 'ie', 'it', 'lt', 'lu', 'lv', 'mt', 'nl', 'pl', 'pt', 'ro', 'se', 'si', 'sk', 'uk']);
const FALLBACK_GALLERY_IMAGE = '/placeholders/business-photos-coming-soon.png';

function Flag({ countryCode, languageCode, label }: { countryCode?: string; languageCode: string; label: string }) {
  const [failed, setFailed] = useState(false);
  const normalizedCountry = countryCode?.toLowerCase();
  // The existing English asset is named uk.png while its language mapping is GB.
  const assetCode = normalizedCountry === 'gb' ? 'uk' : normalizedCountry;
  const hasAsset = Boolean(assetCode && FLAG_ASSET_CODES.has(assetCode) && !failed);
  if (!hasAsset) return <span className="rounded border border-white/35 bg-white/10 px-1.5 py-1 text-[10px] font-bold uppercase" title={label} aria-label={label}>{languageCode.toUpperCase()}</span>;
  return <span className="inline-flex h-6 min-w-7 items-center justify-center overflow-hidden rounded border border-white/35 bg-white/10" title={label} aria-label={label}><img src={`/images/flags/${assetCode}.png`} alt="" className="h-full w-auto object-cover" onError={() => setFailed(true)} /><span className="sr-only">{label}</span></span>;
}

function Field({ label, value, field, type = 'text', multiline = false, shown, onChange, onVisibilityChange, showDisplayLabel = true }: { label: string; value?: string; field: string; type?: string; multiline?: boolean; shown: boolean; onChange?: Props['onChange']; onVisibilityChange?: (value: boolean) => void; showDisplayLabel?: boolean }) {
  if (!onChange && multiline) return shown ? <div className="postcard-description-field min-w-0 rounded-lg border border-white/20 bg-slate-950/35 p-2 text-left shadow-sm backdrop-blur-[2px]" aria-label={`${label}: ${value || ''}`}><span className={showDisplayLabel ? 'mb-1 block text-[10px] font-black uppercase tracking-wider text-white/75' : 'sr-only'}>{label}</span><p className="break-words whitespace-pre-wrap text-sm font-bold leading-5 text-white/90">{value || ''}</p></div> : null;
  if (!onChange) return <div className={`postcard-clean-field min-w-0 rounded-lg border border-white/20 bg-slate-950/35 p-2 text-left shadow-sm backdrop-blur-[2px]${shown ? '' : ' invisible'}`} aria-label={`${label}: ${value || ''}`} aria-hidden={!shown || undefined}><span className={showDisplayLabel ? 'mb-1 block text-[10px] font-black uppercase tracking-wider text-white/75' : 'sr-only'}>{label}</span><p className="truncate text-sm font-bold leading-5 text-white/90">{value || ''}</p></div>;
  return <label className={`postcard-editor-field relative block min-w-0 rounded-lg border border-white/25 bg-slate-950/40 p-1 text-left shadow-sm backdrop-blur-[2px] ${field === 'business_type' ? 'postcard-business-type-field ' : ''}${field === 'website' ? 'postcard-website-editor-field ' : ''}${!shown ? 'opacity-60' : ''}`}>
    <span className="sr-only">{label}</span>
    {onVisibilityChange && <button type="button" aria-label={`${shown ? 'Hide' : 'Show'} ${label} publicly`} title={`${shown ? 'Hide' : 'Show'} ${label} publicly`} onClick={() => onVisibilityChange(!shown)} className="absolute right-1 top-1 z-10 inline-flex items-center gap-1 rounded px-1 text-[9px] leading-none text-white/70 hover:bg-white/10 hover:text-white">{shown ? <Eye className="h-3 w-3" aria-hidden="true" /> : <EyeOff className="h-3 w-3" aria-hidden="true" />}{shown ? 'Shown' : 'Hidden'}</button>}
    {multiline ? <textarea aria-label={label} placeholder={label} value={value || ''} onChange={(event) => onChange(field, event.target.value)} rows={4} className="postcard-editor-input postcard-description-input block h-full min-h-0 w-full resize-y overflow-y-hidden break-words whitespace-pre-wrap border border-white/20 bg-transparent p-2 pr-12 text-sm font-bold leading-7 text-white outline-none placeholder:text-white/50 transition focus:border-white/70 focus:ring-2 focus:ring-white/50" /> : <input aria-label={label} placeholder={label} type={type} value={value || ''} onChange={(event) => onChange(field, event.target.value)} className="postcard-editor-input w-full min-w-0 border border-white/20 bg-transparent p-2 pr-12 text-sm font-bold text-white outline-none placeholder:text-white/50 transition focus:border-white/70 focus:ring-2 focus:ring-white/50" />}
  </label>;
}

function VisibilityButton({ label, shown, onChange }: { label: string; shown: boolean; onChange: (value: boolean) => void }) {
  const Icon = shown ? Eye : EyeOff;
  return <button type="button" onClick={() => onChange(!shown)} className="absolute right-1 top-1 inline-flex items-center gap-1 rounded px-1.5 py-1 text-[10px] font-bold text-white/75 hover:bg-white/10 hover:text-white" aria-label={`${shown ? 'Hide' : 'Show'} ${label} publicly`} title={`${shown ? 'Hide' : 'Show'} ${label} publicly`}><Icon className="h-3 w-3" aria-hidden="true" />{shown ? 'Shown' : 'Hidden'}</button>;
}

function ContactField({ label, value, icon: Icon, href, accent, centered = false }: { label: string; value?: string; icon: LucideIcon; href?: string; accent: string; centered?: boolean }) {
  if (!value) return null;
  return <div className="flex min-w-0 items-start gap-2 rounded-lg border border-white/20 bg-slate-950/35 p-2 text-left shadow-sm backdrop-blur-[2px]" title={label} aria-label={`${label}: ${value}`}>
    <Icon className="mt-0.5 h-4 w-4 shrink-0" style={{ color: accent }} aria-hidden="true" />
    {href ? <a href={href} target={href.startsWith('http') ? '_blank' : undefined} rel={href.startsWith('http') ? 'noreferrer' : undefined} className={`min-w-0 break-all text-sm font-bold leading-5 text-white underline-offset-2 hover:underline${centered ? ' flex-1 text-center' : ''}`} aria-label={`${label}: ${value}`}>{value}</a> : <span className={`min-w-0 break-all text-sm font-bold leading-5 text-white${centered ? ' flex-1 text-center' : ''}`}>{value}</span>}
    <span className="sr-only">{label}</span>
  </div>;
}

function PublicProfileContent({ listing, accent, category, shown, address, languageNames, visibleLanguages, remainingLanguages, galleryImages, galleryIsFallback, onImageClick, editing, categories, cityOptions, onChange, onLogoUpload, uploading }: { listing: CanvasValue; accent: string; category: string; shown: (field: string) => boolean; address: string; languageNames: string; visibleLanguages: string[]; remainingLanguages: number; galleryImages: string[]; galleryIsFallback: boolean; onImageClick: (index: number) => void; editing: boolean; categories: Array<{ id: number; name: string }>; cityOptions: Array<{ id: number; name: string }>; onChange?: Props['onChange']; onLogoUpload?: Props['onLogoUpload']; uploading: boolean }) {
  const publicWebsite = shown('website') && listing.website ? (/^https?:\/\//i.test(listing.website) ? listing.website : `https://${listing.website}`) : undefined;
  const publicAddress = shown('address') && address ? address : undefined;
  const publicLocationParts = [shown('city') ? listing.city?.name : '', shown('region') ? listing.region : '', shown('country') ? listing.country?.name : ''].filter(Boolean);
  const contactItems = [
    shown('phone') && listing.phone ? { label: 'Phone', value: listing.phone, icon: Phone, href: `tel:${listing.phone}` } : null,
    shown('whatsapp') && listing.whatsapp_number ? { label: 'WhatsApp', value: listing.whatsapp_number, icon: MessageCircle, href: `https://wa.me/${listing.whatsapp_number.replace(/[^\d]/g, '')}` } : null,
    shown('email') && listing.contact_email ? { label: 'Email', value: listing.contact_email, icon: Mail, href: `mailto:${listing.contact_email}` } : null,
  ].filter(Boolean) as Array<{ label: string; value: string; icon: LucideIcon; href: string }>;
  const updateVisibility = (field: string, value: boolean) => onChange?.('visibility', { ...(listing.visibility || {}), [field]: value });
  return <div className="absolute inset-[5%] flex flex-col rounded-xl p-[5%] text-white sm:inset-[7%] sm:p-[5%]">
    <header className="flex flex-col gap-5 sm:flex-row sm:items-start sm:gap-6">
      {editing && onLogoUpload ? <label className="flex h-24 w-24 shrink-0 cursor-pointer items-center justify-center overflow-hidden rounded-2xl border-2 border-white bg-white/90 text-center text-xs font-black text-slate-700 shadow-lg sm:h-32 sm:w-32"><input type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={(event) => onLogoUpload(event.target.files?.[0])} className="sr-only" />{listing.logo_url ? <img src={listing.logo_url} alt="Business logo" className="h-full w-full object-contain" /> : <span><ImagePlus className="mx-auto h-5 w-5" />Logo</span>}</label> : listing.logo_url ? <img src={listing.logo_url} alt={`${listing.name} logo`} className="h-24 w-24 shrink-0 rounded-2xl bg-white object-contain p-2 shadow-lg sm:h-32 sm:w-32" /> : <div className="flex h-24 w-24 shrink-0 items-center justify-center rounded-2xl bg-white/15 text-4xl font-black sm:h-32 sm:w-32">{listing.name.slice(0, 1).toUpperCase() || 'L'}</div>}
      <div className="min-w-0 pt-1"><h1 className="break-words text-3xl font-black leading-tight tracking-tight sm:text-5xl">{editing ? <Field label="Business name" field="name" value={listing.name} shown={true} onChange={onChange} showDisplayLabel={false} /> : listing.name}</h1><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm font-semibold text-white/85">{editing ? <label className="rounded-lg border border-white/25 bg-slate-950/40 p-1"><span className="sr-only">Category</span><select aria-label="Category" value={listing.category_id ?? ''} onChange={(event) => onChange?.('category_id', Number(event.target.value) || '')} className="postcard-editor-input rounded border border-white/25 bg-transparent px-2 py-1 text-xs font-bold text-white"><option value="">{category || 'Select category'}</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : <span>Category: {category || 'Business'}</span>}{editing ? <Field label="Business type" field="business_type" value={listing.business_type} shown={shown('business_type')} onChange={onChange} onVisibilityChange={(value) => updateVisibility('business_type', value)} showDisplayLabel={false} /> : shown('business_type') && listing.business_type && <span>Business type: {listing.business_type}</span>}</div><div className="mt-3 flex flex-wrap items-center gap-1.5" aria-label={languageNames || 'No spoken languages configured'}><span className="mr-1 text-sm font-semibold text-white/85">We speak:</span>{visibleLanguages.map((code) => <Flag key={code} countryCode={spokenLanguageDetails(code)?.flagCountryCode} languageCode={code} label={spokenLanguageName(code)} />)}{remainingLanguages > 0 && <span className="rounded border border-white/35 bg-white/10 px-1.5 py-1 text-[10px] font-bold" title={languageNames}>+{remainingLanguages}</span>}{!visibleLanguages.length && <span className="text-sm text-white/70">Not specified</span>}</div></div>
    </header>
    {shown('description') && (editing ? <div className="mt-8"><Field label="Description" field="description" value={listing.description} multiline shown={true} onChange={onChange} showDisplayLabel={false} /></div> : listing.description && <p className="mt-10 max-w-4xl whitespace-pre-wrap break-words text-base font-semibold leading-8 text-white/95 drop-shadow-sm sm:text-lg">{listing.description}</p>)}
    {galleryImages.length > 0 && <div className={`mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4${galleryIsFallback ? ' postcard-gallery-fallback' : ''}`} aria-label={galleryIsFallback ? 'Business photos coming soon' : 'Business photos'}>{galleryImages.map((image, index) => <button key={`${image}-${index}`} type="button" onClick={() => !editing && onImageClick(index)} className={`group relative aspect-[3/2] overflow-hidden rounded-xl text-left${editing ? ' cursor-default' : ''}`} aria-label={galleryIsFallback ? 'View business photos placeholder' : `${listing.name} business photo ${index + 1}`}><img src={image} alt={galleryIsFallback ? 'Business photos coming soon' : `${listing.name} business photo ${index + 1}`} loading={index === 0 ? 'eager' : 'lazy'} className="h-full w-full object-cover transition group-hover:scale-105" />{!galleryIsFallback && !editing && <span className="absolute inset-x-0 bottom-0 bg-slate-950/55 px-2 py-1 text-center text-[10px] font-bold text-white opacity-0 transition group-hover:opacity-100">View photo</span>}</button>)}</div>}
      <div className="mt-auto pt-10">
      {editing ? <div className="grid items-start justify-items-stretch gap-2 border-y border-white/20 py-4 sm:grid-cols-2 lg:grid-cols-[minmax(10rem,2fr)_minmax(5rem,0.8fr)_minmax(8rem,1.2fr)_minmax(8rem,1fr)_minmax(8rem,1fr)]"><div className="relative"><Field label="Street + number" field="address_line1" value={listing.address_line1 || listing.address} shown={shown('address')} onChange={onChange} onVisibilityChange={(value) => updateVisibility('address', value)} showDisplayLabel={false} /></div><Field label="Postcode" field="postal_code" value={listing.postal_code} shown={shown('address')} onChange={onChange} showDisplayLabel={false} /><div className="relative"><Field label="Region" field="region" value={listing.region} shown={shown('region')} onChange={onChange} onVisibilityChange={(value) => updateVisibility('region', value)} showDisplayLabel={false} /></div><div className="relative"><select aria-label="City" value={listing.city_id ?? ''} onChange={(event) => onChange?.('city_id', Number(event.target.value) || '')} className="postcard-editor-input w-full rounded border border-white/25 bg-slate-950/40 px-2 py-2 text-xs font-bold text-white"><option value="">{listing.city?.name || 'Select city'}</option>{cityOptions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><VisibilityButton label="city" shown={shown('city')} onChange={(value) => updateVisibility('city', value)} /></div><div className="relative rounded-lg border border-white/25 bg-slate-950/40 p-2 text-left"><p className="flex items-center gap-2 text-sm font-semibold text-white/90"><Flag countryCode={listing.country?.code} languageCode={listing.country?.code || 'EU'} label={listing.country?.name || 'Country'} />{listing.country?.name || 'Country'}</p><VisibilityButton label="country" shown={shown('country')} onChange={(value) => updateVisibility('country', value)} /></div></div> : (publicAddress || publicLocationParts.length > 0) && <div className="flex flex-wrap items-center justify-center gap-x-3 gap-y-2 border-y border-white/20 py-4 text-sm font-semibold text-white/90"><MapPin className="h-5 w-5 shrink-0" style={{ color: accent }} aria-hidden="true" />{publicAddress && <span>{publicAddress}</span>}{publicAddress && publicLocationParts.length > 0 && <span className="text-white/45" aria-hidden="true">|</span>}{publicLocationParts.map((part, index) => <span key={`${part}-${index}`} className="inline-flex items-center gap-3">{index > 0 && <span className="text-white/45" aria-hidden="true">|</span>}{part}</span>)}</div>}
      {editing ? <div className="mt-5 grid gap-2 sm:grid-cols-3">{[['Phone', 'phone', listing.phone], ['WhatsApp', 'whatsapp_number', listing.whatsapp_number], ['Public email', 'contact_email', listing.contact_email]].map(([label, field, value]) => <Field key={field as string} label={label as string} field={field as string} value={value as string} shown={shown(field as string)} onChange={onChange} onVisibilityChange={(next) => updateVisibility(field as string, next)} showDisplayLabel={false} />)}</div> : contactItems.length > 0 && <div className="mt-5 flex flex-wrap justify-center gap-x-6 gap-y-3 text-sm font-bold">{contactItems.map(({ label, value, icon: Icon, href }) => <a key={label} href={href} className="inline-flex min-w-0 items-center gap-2 text-white underline-offset-2 hover:underline"><Icon className="h-5 w-5 shrink-0" style={{ color: accent }} aria-hidden="true" /><span className="break-all">{value}</span><span className="sr-only">{label}</span></a>)}</div>}
      {editing ? <div className="mt-5 text-center"><Field label="Website" field="website" value={listing.website} shown={shown('website')} onChange={onChange} onVisibilityChange={(value) => updateVisibility('website', value)} showDisplayLabel={false} /></div> : publicWebsite && <div className="mt-5 text-center"><a href={publicWebsite} target="_blank" rel="noreferrer" className="inline-flex max-w-full items-center gap-2 break-all text-base font-extrabold text-white underline decoration-white/50 underline-offset-4 hover:decoration-white sm:text-lg"><Globe2 className="postcard-website-globe h-5 w-5 shrink-0" style={{ color: accent }} aria-hidden="true" />{listing.website}</a></div>}
    </div>
  </div>;
}

export default function PostcardCanvas({ listing, mode, categories = [], cityOptions = [], onChange, onLogoUpload, onBackgroundUpload, uploading = false, allowMediaUpload = true }: Props) {
  const [lightboxIndex, setLightboxIndex] = useState<number | null>(null);
  const editing = mode === 'editing';
  const visibility = listing.visibility || {};
  const shown = (field: string) => visibility[field] !== false;
  const setVisibility = (field: string, value: boolean) => onChange?.('visibility', { ...visibility, [field]: value });
  const address = [listing.address_line1 || listing.address, listing.postal_code].filter(Boolean).join(', ');
  const location = [listing.city?.name, listing.region, listing.country?.name].filter(Boolean).join(', ');
  const category = categories.find((item) => item.id === Number(listing.category_id))?.name || listing.category?.name || '';
  const languageCodes = normalizeSpokenLanguages(listing.languages);
  const languageNames = languageCodes.map(spokenLanguageName).join(', ');
  const visibleLanguages = languageCodes.slice(0, 5);
  const remainingLanguages = Math.max(0, languageCodes.length - visibleLanguages.length);
  const { accent, overlay, overlayOpacity, background } = resolvePresentationStyle(listing);
  const uploadedGalleryImages = (listing.gallery_images || []).filter(Boolean).slice(0, 4);
  const galleryImages = uploadedGalleryImages.length > 0 || editing ? uploadedGalleryImages : [FALLBACK_GALLERY_IMAGE];
  const galleryIsFallback = uploadedGalleryImages.length === 0 && !editing;
  useEffect(() => {
    if (lightboxIndex === null || galleryImages.length === 0) return undefined;
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') setLightboxIndex(null);
      if (event.key === 'ArrowLeft') setLightboxIndex((current) => current === null ? null : (current - 1 + galleryImages.length) % galleryImages.length);
      if (event.key === 'ArrowRight') setLightboxIndex((current) => current === null ? null : (current + 1) % galleryImages.length);
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [lightboxIndex, galleryImages.length]);
  return <article className={`postcard-canvas relative mx-auto w-full max-w-5xl overflow-hidden rounded-2xl border-4 bg-slate-900 shadow-xl${mode === 'public' ? ' postcard-public' : mode === 'editing' ? ' postcard-editor-profile' : ''}`} style={{ borderColor: accent, aspectRatio: mode === 'public' || mode === 'editing' ? 'auto' : `${POSTCARD_CANVAS_WIDTH} / ${POSTCARD_CANVAS_HEIGHT}`, '--postcard-accent': accent } as CSSProperties} aria-label={editing ? 'Visual postcard editor' : 'Claimed listing postcard'}>
    <div className="absolute inset-0 bg-cover bg-center bg-no-repeat" style={{ backgroundImage: `url(${background})`, backgroundSize: 'cover', backgroundPosition: 'center', backgroundRepeat: 'no-repeat' }} />
    <div className="absolute inset-0" style={{ backgroundColor: overlay, opacity: overlayOpacity }} />
    {editing && allowMediaUpload && onBackgroundUpload && <label className="absolute right-3 top-3 z-10 inline-flex cursor-pointer items-center gap-1 rounded-full bg-black/45 px-3 py-2 text-xs font-bold text-white backdrop-blur hover:bg-black/65"><ImagePlus className="h-4 w-4" />Change background<input type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={(event) => onBackgroundUpload(event.target.files?.[0])} className="sr-only" /></label>}
    {mode === 'public' || mode === 'editing' ? <div className="postcard-public-profile"><PublicProfileContent listing={listing} accent={accent} category={category} shown={shown} address={address} languageNames={languageNames} visibleLanguages={visibleLanguages} remainingLanguages={remainingLanguages} galleryImages={galleryImages} galleryIsFallback={galleryIsFallback} onImageClick={setLightboxIndex} editing={editing} categories={categories} cityOptions={cityOptions || []} onChange={onChange} onLogoUpload={onLogoUpload} uploading={uploading} /></div> : <div className="absolute inset-[6%] flex flex-col rounded-xl border p-[4%] text-white sm:inset-[8%] sm:p-[4%]" style={{ borderColor: accent }}>
      <div className="grid min-h-0 grid-cols-[3.75rem_1fr] items-start gap-3 sm:grid-cols-[5.5rem_1fr] sm:gap-4">
        {editing && allowMediaUpload && onLogoUpload ? <label className="flex aspect-square cursor-pointer items-center justify-center overflow-hidden rounded-xl border-2 border-white bg-white/90 text-center text-xs font-black text-slate-700 shadow-lg"><input type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={(event) => onLogoUpload(event.target.files?.[0])} className="sr-only" />{listing.logo_url ? <img src={listing.logo_url} alt="Business logo" className="h-full w-full object-contain" /> : <span><ImagePlus className="mx-auto h-5 w-5" />Logo</span>}</label> : listing.logo_url ? <img src={listing.logo_url} alt={`${listing.name} logo`} className="aspect-square rounded-xl border-2 border-white bg-white object-contain" /> : <div className="flex aspect-square items-center justify-center rounded-xl border-2 border-white/80 bg-white/15 text-2xl font-black">{listing.name.slice(0, 1).toUpperCase() || 'L'}</div>}
        <div className="relative min-w-0 space-y-1"><Field label="Business name" field="name" value={listing.name} shown={true} onChange={onChange} showDisplayLabel={false} />{shown('address') && address && <p className="truncate text-xs font-semibold text-white/80">{address}</p>}{editing && <VisibilityButton label="address" shown={shown('address')} onChange={(value) => setVisibility('address', value)} />}<p className="truncate text-sm font-black text-white">{shown('city') ? (location || 'City, country') : 'Location hidden'}</p>{editing && <VisibilityButton label="location" shown={shown('city')} onChange={(value) => setVisibility('city', value)} />}{editing && <div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="relative block rounded-lg border border-white/25 bg-slate-950/40 p-1 text-left"><span className="sr-only">Category</span><select aria-label="Category" value={listing.category_id ?? ''} onChange={(event) => onChange?.('category_id', Number(event.target.value) || '')} className="postcard-editor-input w-full rounded border border-white/25 bg-slate-950/40 px-1 py-1 text-xs font-bold text-white outline-none"><option value="">{category || 'Select category'}</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Field label="Business type" field="business_type" value={listing.business_type} shown={shown('business_type')} onChange={onChange} onVisibilityChange={(value) => setVisibility('business_type', value)} showDisplayLabel={false} /></div>}{editing && <div className="mt-2 flex flex-wrap items-center gap-1.5 text-xs font-semibold text-white/85" aria-label={languageNames || 'No spoken languages configured'}><span className="mr-1">We speak:</span>{visibleLanguages.map((code) => <Flag key={code} countryCode={spokenLanguageDetails(code)?.flagCountryCode} languageCode={code} label={spokenLanguageName(code)} />)}{!visibleLanguages.length && <span>Not specified</span>}</div>}</div>
      </div>
      <div className={`postcard-description-slot mt-[3%] flex-none${editing ? ' postcard-description-editing' : ''}`}><div className="postcard-description-region"><Field label="Description" field="description" value={listing.description} multiline shown={shown('description')} onChange={editing ? onChange : undefined} onVisibilityChange={editing ? (value) => setVisibility('description', value) : undefined} showDisplayLabel={false} /></div></div>
      {galleryImages.length > 0 && <div className={`mt-[3%] grid grid-cols-2 gap-3 sm:grid-cols-4${galleryIsFallback ? ' postcard-gallery-fallback' : ''}`} aria-label={galleryIsFallback ? 'Business photos coming soon' : 'Business photos'}>{galleryImages.map((image, index) => <button key={`${image}-${index}`} type="button" onClick={() => !editing && setLightboxIndex(index)} className={`group relative aspect-[4/3] overflow-hidden rounded-lg text-left${editing ? ' cursor-default' : ' cursor-zoom-in'}`} aria-label={galleryIsFallback ? 'View business photos placeholder' : editing ? `${listing.name} business photo ${index + 1}` : `View ${listing.name} business photo ${index + 1}`}><img src={image} alt={galleryIsFallback ? 'Business photos coming soon' : `${listing.name} business photo ${index + 1}`} loading={index === 0 ? 'eager' : 'lazy'} className="h-full w-full object-cover transition group-hover:scale-105" />{!editing && !galleryIsFallback && <span className="absolute inset-x-0 bottom-0 bg-slate-950/55 px-2 py-1 text-center text-[10px] font-bold text-white opacity-0 transition group-hover:opacity-100">View photo</span>}</button>)}</div>}
      <div className="postcard-lower-fields mt-[3%] grid min-h-0 grid-cols-1 gap-3 sm:grid-cols-[1.15fr_1.35fr_1.1fr] sm:items-start">
        <div className="flex min-w-0 flex-col gap-2">{editing ? <label className="postcard-editor-field relative block min-w-0 rounded-lg border border-white/25 bg-slate-950/40 p-1 text-left shadow-sm backdrop-blur-[2px]"><span className="sr-only">Category</span><select aria-label="Category" value={listing.category_id ?? ''} onChange={(event) => onChange?.('category_id', Number(event.target.value) || '')} className="postcard-editor-input w-full rounded border border-white/25 bg-slate-950/40 px-1 py-1 text-xs font-bold text-white outline-none transition focus:border-white/70 focus:ring-2 focus:ring-white/50"><option value="">{category || 'Select category'}</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : category && <div className="rounded-lg border border-white/20 bg-slate-950/35 p-2 text-left shadow-sm backdrop-blur-[2px]" aria-label={`Category: ${category}`}><span className="sr-only">Category</span><p className="break-words text-sm font-black text-white">{category}</p></div>}<Field label="Business type" field="business_type" value={listing.business_type} shown={shown('business_type')} onChange={onChange} onVisibilityChange={(value) => setVisibility('business_type', value)} showDisplayLabel={false} /></div>
        <div className="min-w-0 space-y-2"><div className="postcard-website-region mt-2 text-center">{editing ? <Field label="Website" field="website" type="url" value={listing.website} shown={shown('website')} onChange={onChange} onVisibilityChange={(value) => setVisibility('website', value)} /> : <ContactField label="Website" value={shown('website') ? listing.website : undefined} icon={Globe2} accent={accent} centered href={listing.website ? (/^https?:\/\//i.test(listing.website) ? listing.website : `https://${listing.website}`) : undefined} />}</div><div className="postcard-languages min-w-0 text-center"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-white/80">We speak</p><div className="mt-1 flex flex-wrap justify-center gap-1" aria-label={languageNames || 'No spoken languages configured'}>{visibleLanguages.map((code) => <Flag key={code} countryCode={spokenLanguageDetails(code)?.flagCountryCode} languageCode={code} label={spokenLanguageName(code)} />)}{remainingLanguages > 0 && <span className="rounded border border-white/35 bg-white/10 px-1.5 py-1 text-[10px] font-bold" title={languageNames}>+{remainingLanguages}</span>}</div>{!visibleLanguages.some((code) => spokenLanguageDetails(code)?.flagCountryCode && FLAG_ASSET_CODES.has(spokenLanguageDetails(code)?.flagCountryCode?.toLowerCase() === 'gb' ? 'uk' : spokenLanguageDetails(code)?.flagCountryCode?.toLowerCase() || '')) && languageNames && <p className="mt-1 text-[10px] font-semibold text-white/85">{languageNames}</p>}</div></div>
        <div className="min-w-0 space-y-1">{editing ? <><Field label="Phone" field="phone" value={listing.phone} shown={shown('phone')} onChange={onChange} onVisibilityChange={(value) => setVisibility('phone', value)} /><Field label="WhatsApp" field="whatsapp_number" value={listing.whatsapp_number} shown={shown('whatsapp')} onChange={onChange} onVisibilityChange={(value) => setVisibility('whatsapp', value)} /><Field label="Email" field="contact_email" type="email" value={listing.contact_email} shown={shown('email')} onChange={onChange} onVisibilityChange={(value) => setVisibility('email', value)} /></> : <><ContactField label="Phone" value={shown('phone') ? listing.phone : undefined} icon={Phone} accent={accent} href={listing.phone ? `tel:${listing.phone}` : undefined} /><ContactField label="WhatsApp" value={shown('whatsapp') ? listing.whatsapp_number : undefined} icon={MessageCircle} accent={accent} href={listing.whatsapp_number ? `https://wa.me/${listing.whatsapp_number.replace(/[^\d]/g, '')}` : undefined} /><ContactField label="Email" value={shown('email') ? listing.contact_email : undefined} icon={Mail} accent={accent} href={listing.contact_email ? `mailto:${listing.contact_email}` : undefined} /></>}</div>
      </div>
    </div>}
    {lightboxIndex !== null && galleryImages[lightboxIndex] && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/90 p-4" role="dialog" aria-modal="true" aria-label={`${listing.name} business photo viewer`} onKeyDown={(event) => { if (event.key === 'Escape') setLightboxIndex(null); if (event.key === 'ArrowLeft') setLightboxIndex((lightboxIndex - 1 + galleryImages.length) % galleryImages.length); if (event.key === 'ArrowRight') setLightboxIndex((lightboxIndex + 1) % galleryImages.length); }} tabIndex={-1}><button type="button" onClick={() => setLightboxIndex(null)} className="absolute right-4 top-4 rounded-full bg-white p-2 text-slate-900" aria-label="Close photo viewer"><X className="h-5 w-5" /></button>{galleryImages.length > 1 && <button type="button" onClick={() => setLightboxIndex((lightboxIndex - 1 + galleryImages.length) % galleryImages.length)} className="absolute left-3 rounded-full bg-white p-2 text-slate-900 sm:left-6" aria-label="Previous photo"><ChevronLeft className="h-6 w-6" /></button>}<img src={galleryImages[lightboxIndex]} alt={galleryIsFallback ? 'Business photos coming soon' : `${listing.name} business photo ${lightboxIndex + 1}`} className="max-h-[88vh] max-w-[92vw] rounded-lg object-contain" />{galleryImages.length > 1 && <button type="button" onClick={() => setLightboxIndex((lightboxIndex + 1) % galleryImages.length)} className="absolute right-3 rounded-full bg-white p-2 text-slate-900 sm:right-6" aria-label="Next photo"><ChevronRight className="h-6 w-6" /></button>}</div>}
  </article>;
}
