from django.conf import settings
from django.urls import path

from .views import (
    BusinessDetail,
    BusinessList,
    BusinessSearchView,
    CategoryList,
    CityList,
    CountryList,
    CountryStatsListView,
    DebugListingsSampleView,
    FeaturedBusinessListView,
    FilteredCategoryListView,
    FilteredCityListView,
    FilteredCountryListView,
    FilteredTownListView,
    TopCitiesView,
    TopCountriesWithCategoriesView,
    TownList,
    create_claim,
    verify_claim,
)
from .dashboard import (
    DashboardBusinessDetailView,
    DashboardClaimedListingDraftView,
    DashboardClaimedListingPublishView,
    DashboardClaimedListingUnpublishView,
    DashboardBusinessLogoView,
    DashboardClaimedListingBackgroundView,
    DashboardBusinessesView,
    DashboardAuthView,
    DashboardDescriptionAssistView,
    DashboardLogoutView,
    DashboardPasswordChangeView,
    DashboardTrialView,
    DashboardWebsiteView,
    DashboardWebsiteTrialView,
    CreateBusinessView,
    AccountVerificationView,
    AccountVerificationResendView,
)
from .website_editor import DashboardWebsitePublishView, DashboardWebsiteUnpublishView, PublicGeneratedWebsiteView


urlpatterns = [
    path("dashboard/auth/", DashboardAuthView.as_view(), name="dashboard-auth"),
    path("account/verify/", AccountVerificationView.as_view(), name="account-verify"),
    path("account/resend-verification/", AccountVerificationResendView.as_view(), name="account-resend-verification"),
    path("dashboard/businesses/", DashboardBusinessesView.as_view(), name="dashboard-businesses"),
    path("dashboard/businesses/<int:business_id>/", DashboardBusinessDetailView.as_view(), name="dashboard-business-detail"),
    path("dashboard/businesses/<int:business_id>/claimed-listing/draft/", DashboardClaimedListingDraftView.as_view(), name="dashboard-claimed-listing-draft"),
    path("dashboard/businesses/<int:business_id>/claimed-listing/publish/", DashboardClaimedListingPublishView.as_view(), name="dashboard-claimed-listing-publish"),
    path("dashboard/businesses/<int:business_id>/claimed-listing/unpublish/", DashboardClaimedListingUnpublishView.as_view(), name="dashboard-claimed-listing-unpublish"),
    path("dashboard/businesses/<int:business_id>/logo/", DashboardBusinessLogoView.as_view(), name="dashboard-business-logo"),
    path("dashboard/businesses/<int:business_id>/claimed-listing/background/", DashboardClaimedListingBackgroundView.as_view(), name="dashboard-claimed-listing-background"),
    path("dashboard/businesses/<int:business_id>/trial/", DashboardTrialView.as_view(), name="dashboard-trial"),
    path("dashboard/businesses/<int:business_id>/website/", DashboardWebsiteView.as_view(), name="dashboard-website"),
    path("dashboard/businesses/<int:business_id>/website/trial/", DashboardWebsiteTrialView.as_view(), name="dashboard-website-trial"),
    path("dashboard/businesses/<int:business_id>/website/publish/", DashboardWebsitePublishView.as_view(), name="dashboard-website-publish"),
    path("dashboard/businesses/<int:business_id>/website/unpublish/", DashboardWebsiteUnpublishView.as_view(), name="dashboard-website-unpublish"),
    path("generated-websites/<slug:slug>/", PublicGeneratedWebsiteView.as_view(), name="public-generated-website"),
    path("dashboard/password/", DashboardPasswordChangeView.as_view(), name="dashboard-password"),
    path("dashboard/logout/", DashboardLogoutView.as_view(), name="dashboard-logout"),
    path("dashboard/description-assist/", DashboardDescriptionAssistView.as_view(), name="dashboard-description-assist"),
    path("dashboard/create-business/", CreateBusinessView.as_view(), name="dashboard-create-business"),
    path("businesses/featured/", FeaturedBusinessListView.as_view(), name="featured-businesses"),
    path("businesses/search/", BusinessSearchView.as_view(), name="business-search"),
    path("businesses/", BusinessList.as_view(), name="business-list"),
    path("businesses/<slug:slug>/", BusinessDetail.as_view(), name="business-detail"),
    path("countries/stats/", CountryStatsListView.as_view(), name="country-stats"),
    path("countries/", FilteredCountryListView.as_view(), name="filtered-country-list"),
    path("cities/", FilteredCityListView.as_view(), name="filtered-city-list"),
    path("cities/top/", TopCitiesView.as_view(), name="top-cities"),
    path("countries/top-categories/", TopCountriesWithCategoriesView.as_view(), name="top-countries-categories"),
    path("towns/", FilteredTownListView.as_view(), name="filtered-town-list"),
    path("categories/", FilteredCategoryListView.as_view(), name="filtered-category-list"),
    path("all-countries/", CountryList.as_view(), name="country-list"),
    path("all-cities/", CityList.as_view(), name="city-list"),
    path("all-towns/", TownList.as_view(), name="town-list"),
    path("all-categories/", CategoryList.as_view(), name="category-list"),
    path("claims", create_claim, name="create-claim"),
    path("verify", verify_claim, name="verify-claim"),
]

if settings.EXPOSE_PUBLIC_DEBUG_ENDPOINTS:
    urlpatterns.insert(
        0,
        path("debug/listings-sample/", DebugListingsSampleView.as_view(), name="debug-listings-sample"),
    )
