# Generated by Django 5.0.9 on 2025-12-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='csv_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='csv_source_file',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='imported_from_csv',
            field=models.BooleanField(default=False),
        ),
    ]
