# Generated by Django 5.0.9 on 2025-12-12 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_business_csv_imported_at_business_csv_source_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='listings.country'),
        ),
    ]
