# Generated by Django 5.0.9 on 2025-12-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_business_address_line1_business_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('claimed', 'Claimed'), ('premium', 'Premium')], default='free', help_text='Listing tier determines display layout and available features', max_length=20),
        ),
    ]
