# Generated by Django 5.0.9 on 2025-12-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_add_business_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image_url',
            field=models.URLField(blank=True, help_text='Main business image URL (for Premium tier)'),
        ),
        migrations.AddField(
            model_name='business',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Business logo URL (for Premium tier)'),
        ),
    ]
