# Generated by Django 5.0.9 on 2025-12-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_add_media_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='premium_content',
            field=models.TextField(blank=True, help_text='Rich text content for premium listings (3-4 paragraphs)'),
        ),
        migrations.AddField(
            model_name='business',
            name='premium_images',
            field=models.JSONField(blank=True, default=list, help_text='Additional image URLs for premium listings (max 3-4)'),
        ),
        migrations.AddField(
            model_name='business',
            name='premium_sidebar',
            field=models.JSONField(blank=True, default=dict, help_text='Premium sidebar configuration: highlight, services, contact_email, etc.'),
        ),
    ]
