# Generated by Django 5.0.9 on 2025-12-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_business_premium_content_business_premium_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
