# Generated by Django 5.2.9 on 2025-12-29 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_add_unique_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessclaimrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='businessclaimrequest',
            name='verification_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='businessclaimrequest',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
