# Generated by Django 5.2.9 on 2025-12-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_businessclaimrequest_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="code",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="business",
            name="visibility_country",
            field=models.CharField(
                blank=True,
                help_text="ISO 2-letter country code required when visibility_scope=country.",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="visibility_scope",
            field=models.CharField(
                choices=[("country", "Country"), ("eu", "EU-wide")],
                default="eu",
                help_text="Premium visibility scope (country or EU-wide).",
                max_length=10,
            ),
        ),
    ]
