# Generated by Django 5.2.9 on 2025-12-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0010_country_code_business_visibility_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="premium_layout_width",
            field=models.CharField(
                choices=[("boxed", "Boxed"), ("full", "Full width")],
                default="boxed",
                help_text="Layout width for premium business page.",
                max_length=10,
            ),
        ),
    ]
