# Generated by Django 5.2.17 on 2026-08-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_accountverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='accent_color',
            field=models.CharField(blank=True, default='#2563EB', max_length=7),
        ),
        migrations.AddField(
            model_name='business',
            name='logo_file',
            field=models.ImageField(blank=True, help_text='Uploaded logo image', null=True, upload_to='business_logos/'),
        ),
    ]
