# Generated by Django 5.2.17 on 2026-08-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_publication_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
