# Generated by Django 5.2.17 on 2026-08-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_categorysuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='business',
            name='claimed_background_file',
            field=models.ImageField(blank=True, help_text='Uploaded Claimed Listing background image', null=True, upload_to='business_backgrounds/'),
        ),
        migrations.AddField(
            model_name='business',
            name='spoken_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='business',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
